spring:
  application:
    name:quiz-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true                       # 打印 Hibernate SQL（占位符）
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   # MyBatis 使用 SLF4J 日志

logging:
  level:
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG                      # 打印 Hibernate 生成的 SQL（占位符）
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE   # 打印绑定参数（值）
    com.zaxxer.hikari: INFO

server:
  port: 8083